name: workflow-3

on:
  push:
    branches: [ "main-test" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build nodejs with Docker
        run: docker build -t nodejs-image .

      - name: Verification of images
        run: docker images
        
